from dataclasses import dataclass
import json
import os
from pathlib import Path


FLODIAL_SET = [
    "Choke stuck",
    "Coolant temperature light issue",
    "brake adjusters",
    "Bent axle",
    "Loose connector",
    "Resolution",
    "Spring clips",
    "BIOS power controller",
    "Blown fuse",
    "LCD malfunction",
    "Leak",
    "Worn parts",
    "Loose connections",
    "Loose wire",
    "Tie rod",
    "Starter problem",
    "Transmission issue",
    "Voltage regulator",
    "battery memory effect",
    "Debris",
    "fan or temperature sensor failure",
    "Malfunctioning internal device",
    "Screen rotation",
    "Cotter pin issue",
    "Motherboard failure",
    "battery charger problem",
    "Wheel bearing",
    "rust or malfunctioning return spring",
    "Cable issue",
    "Power management",
    "Battery issue",
    "Ignition system wiring or voltage regulator issue",
    "Video processor",
    "Brake pad issue",
    "Loose rack",
    "Burnt motherboard",
    "Power steering pump issue",
    "Motherboard malfunction",
    "power adapter",
    "engine flush",
    "Water pump leak",
    "Power plan",
    "Bent part",
    "Warped rotor",
    "Fuel injector problem",
    "Power drain",
    "Short circuit",
    "Emergency brake switch",
    "Hard drive failure",
    "Password",
    "Inverter",
    "Blink codes issue",
    "Exhaust leak",
    "Pressure relief system failure",
    "Battery",
    "LCD fault",
    "Power failure",
    "sensor",
    "faulty battery",
    "Pebbles in wheel covers",
    "worn lower ball joint",
    "Alignment",
    "LCD leakage",
    "Wiring issue",
    "Starter relay failure",
    "Power connector issue",
    "Stuck piston or over-adjusted shoes",
    "connector malfunction",
    "DC power jack failure",
    "Corroded battery connectors",
    "malfunctioning motherboard or RAM",
    "ABS failure",
    "Fuel distribution",
    "Incompatibility",
    "Loose lug nuts",
    "Brake wear",
    "Connectivity",
    "Driver issue",
    "CV joints",
    "Cord issue",
    "Backlight",
    "Tire damage",
    "Water pump failure",
    "Broken ignition switch",
    "Overheating shutdown",
    "Hardware failure",
    "Overdischarge",
    "brake problem",
    "ISP issue",
    "cooling system problem",
    "Dead battery",
    "External device interference",
    "Heater core malfunction",
    "Interference",
    "Loose display connectors",
    "Radiator leak",
    "Beep Codes",
    "multiple light failure",
    "Network connectivity issue",
    "Virus/malware identification and OS restoration",
    "Parasitic drain",
    "Expansion/contraction",
    "Overheating",
    "Carburetor issue",
    "Malfunction",
    "Faulty ball joint",
    "Brake pad vibration",
    "Battery replacement",
    "Loose bolt",
    "Blown fusible link",
    "Display issue",
    "Fuel issue",
    "Brake fluid overflow",
    "Power button issue",
    "Bulb failure",
    "Pump failure",
    "Hardware failure or corrupted driver",
    "ABS malfunction",
    "bulb replacement",
    "LCD display issue",
    "Unknown",
    "Video problem",
    "Voltage issue",
    "Battery drain",
    "Oxidation",
    "Boot order issue",
    "Reset",
    "BIOS upgrade causing overheating",
    "High spot on the rotor",
    "Hard drive issue",
    "cap erosion",
    "Mechanical",
    "Router malfunction",
    "spark control system",
    "CCFL malfunction",
    "corrupted Windows installation",
    "Antifreeze leak",
    "Corrupted hard drive",
    "Clogged radiator",
    "Network visibility",
    "Controller failure",
    "Worn steering coupling",
    "Wheel imbalance",
    "Open circuit",
    "Wireless adapter issue",
    "Router reset",
    "CV joint failure",
    "jamming",
    "Thermostat",
    "Drive belt",
    "Non-functional power outlet",
    "cracked coil or cracked distributor",
    "Windows installation problem",
]


@dataclass
class FlodialInstance:
    self_report: str
    target: str


def load_data() -> list[FlodialInstance]:
    data_path = Path(os.path.dirname(__file__), "flodial.json")
    with data_path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    return [
        FlodialInstance(self_report=instance["self_repo"], target=instance["target"])
        for instance in data
    ]


if __name__ == "__main__":
    print(len(load_data()))
